add mem leak checking to fillit test

diff --git a/fillit/run b/fillit/run
--- a/fillit/run
+++ b/fillit/run
@@ -6,20 +6,14 @@ if [[ -z $SRC_DIR ]]; then
 	exit 1;
 fi
 
-DARKGRAY='\033[1;30m'
 RED='\033[0;31m'    
-LIGHTRED='\033[1;31m'
 GREEN='\033[0;32m'    
-YELLOW='\033[1;33m'
-BLUE='\033[0;34m'    
-PURPLE='\033[0;35m'    
-LIGHTPURPLE='\033[1;35m'
 CYAN='\033[0;36m'    
-WHITE='\033[1;37m'
 RESET='\033[0m'
 
 EXE=$SRC_DIR/fillit
-ACTUAL=actual.log
+REPORT=report.log
+OUTPUT=output.log
 
 print_ok() {
 	printf "${GREEN}OK${RESET}\n"
@@ -38,20 +32,25 @@ should_be_correct() {
 }
 
 should_be_the_same() {
-	$EXE $1 > $ACTUAL
+	leaks -q -atExit -- $EXE $1 > $REPORT 2> /dev/null
+	if [[ $? == 1 ]]; then
+		printf "${RED}leaks${RESET} ";
+	fi
+	sed -n '/leaks Report Version: /q;p' $REPORT > $OUTPUT
 	printf "${RED}"
-	diff $2 $ACTUAL && print_ok
+	diff $2 $OUTPUT && print_ok
 	printf "${RESET}"
-	rm $ACTUAL
+	rm $REPORT $OUTPUT
 }
 
 should_be_the_same_with_time() {
-	time $EXE $1 > $ACTUAL
+	time $EXE $1 > $OUTPUT
 	printf "${RED}"
-	diff "$1.correct" $ACTUAL && print_ok
+	diff "$1.correct" $OUTPUT && print_ok
 	printf "${RESET}"
-	rm $ACTUAL
+	rm $OUTPUT
 }
+
 make -s -C $SRC_DIR
 
 printf "${CYAN}===EVAL====FORM=====${RESET}\n"
@@ -65,7 +64,7 @@ should_print_error sandbox/eval_form_incorrect_1.txt
 printf "print error with incorrect format file: "
 should_print_error sandbox/eval_form_incorrect_2.txt
 
-printf "print error when there are 27 tetriminos: "
+printf "there are 27 tetriminos: "
 should_print_error sandbox/27_pieces.txt
 
 printf "easy fillit: "
@@ -77,49 +76,51 @@ should_be_the_same_with_time sandbox/test1
 printf "challenge speed test: "
 should_be_the_same_with_time sandbox/test7
 
-printf "${CYAN}===MY====TEST=======${RESET}\n"
+printf "${CYAN}===ERROR=MANAGEMENT===${RESET}\n"
 
-printf "print error when file does not exist: "
+printf "file not exist: "
 should_print_error sandbox/42.txt
 
-printf "print error when file is empty: "
+printf "file empty: "
 should_print_error sandbox/empty.txt
 
-printf "print error when line length > 4: "
+printf "line length > 4: "
 should_print_error sandbox/too_wide.txt
 
-printf "print error when line length < 4: "
+printf "line length < 4: "
 should_print_error sandbox/too_narrow.txt
 
-printf "print error when more than 4 lines: "
+printf "more than 4 lines: "
 should_print_error sandbox/too_high.txt
 
-printf "print error when less than 4 lines: "
+printf "less than 4 lines: "
 should_print_error sandbox/too_short.txt
 
-printf "print error when there is no newline separating 4x4 square: "
+printf "no newline separating 4x4 square: "
 should_print_error sandbox/no_nl_separator.txt
 
-printf "print error when there are too many newlines separating 4x4 square: "
+printf "too many newlines separating 4x4 square: "
 should_print_error sandbox/too_many_nl.txt
 
-printf "print error when there are more than 4 blocks: "
+printf "more than 4 blocks: "
 should_print_error sandbox/more_than_4_blocks.txt
 
-printf "print error when there are less than 4 blocks: "
+printf "less than 4 blocks: "
 should_print_error sandbox/less_than_4_blocks.txt
 
-printf "print error when there is no blocks"
+printf "no blocks: "
 should_print_error sandbox/no_blocks.txt
 
-printf "print error when there is an invalid char: "
+printf "invalid char: "
 should_print_error sandbox/invalid_char.txt
 
-printf "print error when blocks are not stick together (1): "
+printf "blocks are not stick together (1): "
 should_print_error sandbox/blocks_not_stick_together_1.txt
 
-printf "print error when blocks are not stick together (2): "
+printf "blocks are not stick together (2): "
 should_print_error sandbox/blocks_not_stick_together_2.txt
+
+printf "${CYAN}===FUNCTIONAL==TEST=====${RESET}\n"
 
 printf "test 2: "
 should_be_correct sandbox/test2
@@ -160,8 +161,16 @@ should_be_correct sandbox/test18
 printf "test 19: "
 should_be_correct sandbox/test19
 
-printf "test 20: "
-should_be_correct sandbox/test20
+printf "${CYAN}===MILLON==CHECKER=====${RESET}\n"
+cd millon_checker
+./fillit_checker.zsh -v $SRC_DIR etalon_fillit 1 12
+cd ..
+
+printf "${RESET}"
+read -p "Do you want to run performance testing? [Yes/no]" PERF
+if [[ $PERF != "Yes"  ]]; then
+	exit 0;
+fi
 
 printf "test 13: "
 should_be_the_same_with_time sandbox/test13
@@ -171,7 +180,3 @@ should_be_the_same_with_time sandbox/test14
 
 printf "test 15: "
 should_be_the_same_with_time sandbox/test15
-
-printf "${CYAN}===MILLON==CHECKER=====${RESET}\n"
-cd millon_checker
-./fillit_checker.zsh -v $SRC_DIR etalon_fillit 1 12
